<?xml version="1.0" encoding="utf-8"?><Database Name="eREST_BD" Class="eREST_DigramaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Roberto-PC\ROBERTO;Initial Catalog=eREST_BD;Persist Security Info=True;User ID=sa" SettingsObjectName="eREST.BO.Properties.Settings" SettingsPropertyName="eREST_BDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.eREST_BODEGAS" Member="eREST_BODEGAs">
    <Type Name="eREST_BODEGA">
      <Column Name="BOD_NOMBRE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BOD_ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BOD_LOCALIDAD" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BOD_FK_TIPOBODEGA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BOD_PK_BODEGA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_BODEGA_eREST_SUBBODEGA" Member="eREST_SUBBODEGAs" ThisKey="BOD_PK_BODEGA" OtherKey="SBO_FK_BODEGA" Type="eREST_SUBBODEGA" />
      <Association Name="eREST_TIPOBODEGA_eREST_BODEGA" Member="eREST_TIPOBODEGA" ThisKey="BOD_FK_TIPOBODEGA" OtherKey="TBO_PK_TIPOBODEGA" Type="eREST_TIPOBODEGA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_CANTONES" Member="eREST_CANTONEs">
    <Type Name="eREST_CANTONE">
      <Column Name="CAN_FK_PROVINCIA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CAN_CANTON" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CAN_PK_CANTON" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_CANTONE_eREST_DISTRITO" Member="eREST_DISTRITOs" ThisKey="CAN_PK_CANTON" OtherKey="DIS_FK_CANTON" Type="eREST_DISTRITO" />
      <Association Name="eREST_PROVINCIA_eREST_CANTONE" Member="eREST_PROVINCIA" ThisKey="CAN_FK_PROVINCIA" OtherKey="PRO_PK_PROVINCIA" Type="eREST_PROVINCIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_CATEGORIA" Member="eREST_CATEGORIAs">
    <Type Name="eREST_CATEGORIA">
      <Column Name="CAT_NOMBRE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CAT_PK_CATEGORIA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_CATEGORIA_eREST_SUBCATEGORIA" Member="eREST_SUBCATEGORIAs" ThisKey="CAT_PK_CATEGORIA" OtherKey="SCA_FK_CATEGORIA" Type="eREST_SUBCATEGORIA" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_CONTACTOS" Member="eREST_CONTACTOs">
    <Type Name="eREST_CONTACTO">
      <Column Name="PTC_CONTACTO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PTC_FK_PERSONA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PTC_FK_TIPOCONTACTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TCO_PK_CONTACTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_PERSONA_eREST_CONTACTO" Member="eREST_PERSONA" ThisKey="PTC_FK_PERSONA" OtherKey="PER_PK_PERSONA" Type="eREST_PERSONA" IsForeignKey="true" />
      <Association Name="eREST_TIPOCONTACTO_eREST_CONTACTO" Member="eREST_TIPOCONTACTO" ThisKey="PTC_FK_TIPOCONTACTO" OtherKey="TIP_PK_TIPOCONTACTO" Type="eREST_TIPOCONTACTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_DETALLEORDEN" Member="eREST_DETALLEORDENs">
    <Type Name="eREST_DETALLEORDEN">
      <Column Name="DOR_PK_DETALLEORDEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DOR_FK_PRODUCTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DOR_CANTIDAD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DOR_FK_ORDEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="eREST_ORDEN_eREST_DETALLEORDEN" Member="eREST_ORDEN" ThisKey="DOR_FK_ORDEN" OtherKey="ORD_PK_ORDEN" Type="eREST_ORDEN" IsForeignKey="true" />
      <Association Name="eREST_PRODUCTO_eREST_DETALLEORDEN" Member="eREST_PRODUCTO" ThisKey="DOR_FK_PRODUCTO" OtherKey="PRO_PK_PRODUCTO" Type="eREST_PRODUCTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_DETRECETA" Member="eREST_DETRECETAs">
    <Type Name="eREST_DETRECETA">
      <Column Name="DRE_CANTIDAD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DRE_UMEDIDA" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DRE_FK_RECETA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DRE_FK_INSUMO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DRE_PK_DETRECETA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_INSUMO_eREST_DETRECETA" Member="eREST_INSUMO" ThisKey="DRE_FK_INSUMO" OtherKey="INS_PK_INSUMO" Type="eREST_INSUMO" IsForeignKey="true" />
      <Association Name="eREST_RECETA_eREST_DETRECETA" Member="eREST_RECETA" ThisKey="DRE_FK_RECETA" OtherKey="REC_PK_RECETA" Type="eREST_RECETA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_DETSUBBODEGA" Member="eREST_DETSUBBODEGAs">
    <Type Name="eREST_DETSUBBODEGA">
      <Column Name="DSB_CANTIDAD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DSB_UMEDIDA" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DSB_FK_SUBBODEGA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DSB_FK_PRODUCTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DSB_FK_INSUMO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DSB_PK_DETSUBBODEGA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_INSUMO_eREST_DETSUBBODEGA" Member="eREST_INSUMO" ThisKey="DSB_FK_INSUMO" OtherKey="INS_PK_INSUMO" Type="eREST_INSUMO" IsForeignKey="true" />
      <Association Name="eREST_PRODUCTO_eREST_DETSUBBODEGA" Member="eREST_PRODUCTO" ThisKey="DSB_FK_PRODUCTO" OtherKey="PRO_PK_PRODUCTO" Type="eREST_PRODUCTO" IsForeignKey="true" />
      <Association Name="eREST_SUBBODEGA_eREST_DETSUBBODEGA" Member="eREST_SUBBODEGA" ThisKey="DSB_FK_SUBBODEGA" OtherKey="SBO_PK_SUBBODEGA" Type="eREST_SUBBODEGA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_DIRECCIONES" Member="eREST_DIRECCIONEs">
    <Type Name="eREST_DIRECCIONE">
      <Column Name="DIR_FK_DISTRITO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIR_DESCRIPCION" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DIR_PK_DIRECCION" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_DIRECCIONE_eREST_PERSONA" Member="eREST_PERSONAs" ThisKey="DIR_PK_DIRECCION" OtherKey="PER_FK_DIRECCION" Type="eREST_PERSONA" />
      <Association Name="eREST_DISTRITO_eREST_DIRECCIONE" Member="eREST_DISTRITO" ThisKey="DIR_FK_DISTRITO" OtherKey="DIS_PK_DISTRITO" Type="eREST_DISTRITO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_DISTRITOS" Member="eREST_DISTRITOs">
    <Type Name="eREST_DISTRITO">
      <Column Name="DIS_FK_CANTON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIS_DISTRITO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DIS_PK_DISTRITO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_DISTRITO_eREST_DIRECCIONE" Member="eREST_DIRECCIONEs" ThisKey="DIS_PK_DISTRITO" OtherKey="DIR_FK_DISTRITO" Type="eREST_DIRECCIONE" />
      <Association Name="eREST_CANTONE_eREST_DISTRITO" Member="eREST_CANTONE" ThisKey="DIS_FK_CANTON" OtherKey="CAN_PK_CANTON" Type="eREST_CANTONE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_EMPRESA" Member="eREST_EMPRESAs">
    <Type Name="eREST_EMPRESA">
      <Column Name="EMP_PK_EMPRESA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMP_NOMBRE" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EMP_TELEFONO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EMP_DIRECCION" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="eREST_EMPRESA_eREST_SECTOR" Member="eREST_SECTORs" ThisKey="EMP_PK_EMPRESA" OtherKey="SEC_FK_EMPRESA" Type="eREST_SECTOR" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_INSUMOS" Member="eREST_INSUMOs">
    <Type Name="eREST_INSUMO">
      <Column Name="INS_NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="INS_TAMANNO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="INS_UMEDIDA" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="INS_PK_INSUMO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_INSUMO_eREST_DETRECETA" Member="eREST_DETRECETAs" ThisKey="INS_PK_INSUMO" OtherKey="DRE_FK_INSUMO" Type="eREST_DETRECETA" />
      <Association Name="eREST_INSUMO_eREST_DETSUBBODEGA" Member="eREST_DETSUBBODEGAs" ThisKey="INS_PK_INSUMO" OtherKey="DSB_FK_INSUMO" Type="eREST_DETSUBBODEGA" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_MOBILIARIO" Member="eREST_MOBILIARIOs">
    <Type Name="eREST_MOBILIARIO">
      <Column Name="MOB_PK_MOBILIARIO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MOB_COORX" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MOB_COORY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MOB_ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MOB_FK_TIPOMOBILIARIO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MOB_FK_SECTOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="eREST_MOBILIARIO_eREST_ORDEN" Member="eREST_ORDENs" ThisKey="MOB_PK_MOBILIARIO" OtherKey="ORD_FK_MOBILIARIO" Type="eREST_ORDEN" />
      <Association Name="eREST_SECTOR_eREST_MOBILIARIO" Member="eREST_SECTOR" ThisKey="MOB_FK_SECTOR" OtherKey="SEC_PK_SECTOR" Type="eREST_SECTOR" IsForeignKey="true" />
      <Association Name="eREST_TIPOMOBILIARIO_eREST_MOBILIARIO" Member="eREST_TIPOMOBILIARIO" ThisKey="MOB_FK_TIPOMOBILIARIO" OtherKey="TMO_PK_TIPOMOBILIARIO" Type="eREST_TIPOMOBILIARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_ORDEN" Member="eREST_ORDENs">
    <Type Name="eREST_ORDEN">
      <Column Name="ORD_PK_ORDEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ORD_FK_USUARIO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ORD_FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ORD_ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ORD_IMPUESTO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ORD_TOTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ORD_FK_MOBILIARIO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="eREST_ORDEN_eREST_DETALLEORDEN" Member="eREST_DETALLEORDENs" ThisKey="ORD_PK_ORDEN" OtherKey="DOR_FK_ORDEN" Type="eREST_DETALLEORDEN" />
      <Association Name="eREST_MOBILIARIO_eREST_ORDEN" Member="eREST_MOBILIARIO" ThisKey="ORD_FK_MOBILIARIO" OtherKey="MOB_PK_MOBILIARIO" Type="eREST_MOBILIARIO" IsForeignKey="true" />
      <Association Name="eREST_USUARIO_eREST_ORDEN" Member="eREST_USUARIO" ThisKey="ORD_FK_USUARIO" OtherKey="USU_PK_USUARIO" Type="eREST_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_PERSONAS" Member="eREST_PERSONAs">
    <Type Name="eREST_PERSONA">
      <Column Name="PER_PK_CEDULA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PER_FK_DIRECCION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PER_PNOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PER_ESTADO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="PER_HDELINCUENCIA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PER_SNOMBRE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PER_PAPELLIDO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PER_SAPELLIDO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PER_GENERO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PER_ESTADOCIVIL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PER_NACIONALIDAD" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PER_PK_PERSONA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_PERSONA_eREST_CONTACTO" Member="eREST_CONTACTOs" ThisKey="PER_PK_PERSONA" OtherKey="PTC_FK_PERSONA" Type="eREST_CONTACTO" />
      <Association Name="eREST_DIRECCIONE_eREST_PERSONA" Member="eREST_DIRECCIONE" ThisKey="PER_FK_DIRECCION" OtherKey="DIR_PK_DIRECCION" Type="eREST_DIRECCIONE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_PRODUCTO" Member="eREST_PRODUCTOs">
    <Type Name="eREST_PRODUCTO">
      <Column Name="PRO_NOMBRE" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_UMEDIDA" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="PRO_TAMANNO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_PREPARADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PRO_FK_SUBCATEGORIA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PRO_FK_RECETA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRO_PK_PRODUCTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_PRODUCTO_eREST_DETALLEORDEN" Member="eREST_DETALLEORDENs" ThisKey="PRO_PK_PRODUCTO" OtherKey="DOR_FK_PRODUCTO" Type="eREST_DETALLEORDEN" />
      <Association Name="eREST_PRODUCTO_eREST_DETSUBBODEGA" Member="eREST_DETSUBBODEGAs" ThisKey="PRO_PK_PRODUCTO" OtherKey="DSB_FK_PRODUCTO" Type="eREST_DETSUBBODEGA" />
      <Association Name="eREST_RECETA_eREST_PRODUCTO" Member="eREST_RECETA" ThisKey="PRO_FK_RECETA" OtherKey="REC_PK_RECETA" Type="eREST_RECETA" IsForeignKey="true" />
      <Association Name="eREST_SUBCATEGORIA_eREST_PRODUCTO" Member="eREST_SUBCATEGORIA" ThisKey="PRO_FK_SUBCATEGORIA" OtherKey="SCA_PK_SUBCATEGORIA" Type="eREST_SUBCATEGORIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_PROVINCIAS" Member="eREST_PROVINCIAs">
    <Type Name="eREST_PROVINCIA">
      <Column Name="PRO_PROVINCIA" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_PK_PROVINCIA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_PROVINCIA_eREST_CANTONE" Member="eREST_CANTONEs" ThisKey="PRO_PK_PROVINCIA" OtherKey="CAN_FK_PROVINCIA" Type="eREST_CANTONE" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_RECETA" Member="eREST_RECETAs">
    <Type Name="eREST_RECETA">
      <Column Name="REC_ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="REC_PK_RECETA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_RECETA_eREST_DETRECETA" Member="eREST_DETRECETAs" ThisKey="REC_PK_RECETA" OtherKey="DRE_FK_RECETA" Type="eREST_DETRECETA" />
      <Association Name="eREST_RECETA_eREST_PRODUCTO" Member="eREST_PRODUCTOs" ThisKey="REC_PK_RECETA" OtherKey="PRO_FK_RECETA" Type="eREST_PRODUCTO" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_SECTOR" Member="eREST_SECTORs">
    <Type Name="eREST_SECTOR">
      <Column Name="SEC_PK_SECTOR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEC_NOMBRE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SEC_COORX" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SEC_COORY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SEC_FK_EMPRESA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="eREST_SECTOR_eREST_MOBILIARIO" Member="eREST_MOBILIARIOs" ThisKey="SEC_PK_SECTOR" OtherKey="MOB_FK_SECTOR" Type="eREST_MOBILIARIO" />
      <Association Name="eREST_EMPRESA_eREST_SECTOR" Member="eREST_EMPRESA" ThisKey="SEC_FK_EMPRESA" OtherKey="EMP_PK_EMPRESA" Type="eREST_EMPRESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_SUBBODEGAS" Member="eREST_SUBBODEGAs">
    <Type Name="eREST_SUBBODEGA">
      <Column Name="SBO_FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SBO_ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SBO_FK_BODEGA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SBO_PK_SUBBODEGA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_SUBBODEGA_eREST_DETSUBBODEGA" Member="eREST_DETSUBBODEGAs" ThisKey="SBO_PK_SUBBODEGA" OtherKey="DSB_FK_SUBBODEGA" Type="eREST_DETSUBBODEGA" />
      <Association Name="eREST_BODEGA_eREST_SUBBODEGA" Member="eREST_BODEGA" ThisKey="SBO_FK_BODEGA" OtherKey="BOD_PK_BODEGA" Type="eREST_BODEGA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_SUBCATEGORIA" Member="eREST_SUBCATEGORIAs">
    <Type Name="eREST_SUBCATEGORIA">
      <Column Name="SCA_NOMBRE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SCA_FK_CATEGORIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCA_PK_SUBCATEGORIA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_SUBCATEGORIA_eREST_PRODUCTO" Member="eREST_PRODUCTOs" ThisKey="SCA_PK_SUBCATEGORIA" OtherKey="PRO_FK_SUBCATEGORIA" Type="eREST_PRODUCTO" />
      <Association Name="eREST_CATEGORIA_eREST_SUBCATEGORIA" Member="eREST_CATEGORIA" ThisKey="SCA_FK_CATEGORIA" OtherKey="CAT_PK_CATEGORIA" Type="eREST_CATEGORIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_TIPOBODEGA" Member="eREST_TIPOBODEGAs">
    <Type Name="eREST_TIPOBODEGA">
      <Column Name="TBO_NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TBO_PK_TIPOBODEGA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_TIPOBODEGA_eREST_BODEGA" Member="eREST_BODEGAs" ThisKey="TBO_PK_TIPOBODEGA" OtherKey="BOD_FK_TIPOBODEGA" Type="eREST_BODEGA" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_TIPOCONTACTO" Member="eREST_TIPOCONTACTOs">
    <Type Name="eREST_TIPOCONTACTO">
      <Column Name="TIP_NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TIP_PK_TIPOCONTACTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="eREST_TIPOCONTACTO_eREST_CONTACTO" Member="eREST_CONTACTOs" ThisKey="TIP_PK_TIPOCONTACTO" OtherKey="PTC_FK_TIPOCONTACTO" Type="eREST_CONTACTO" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_TIPOMOBILIARIO" Member="eREST_TIPOMOBILIARIOs">
    <Type Name="eREST_TIPOMOBILIARIO">
      <Column Name="TMO_PK_TIPOMOBILIARIO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TMO_NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TMO_IMAGEN" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="TMO_DESCRIPCION" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="eREST_TIPOMOBILIARIO_eREST_MOBILIARIO" Member="eREST_MOBILIARIOs" ThisKey="TMO_PK_TIPOMOBILIARIO" OtherKey="MOB_FK_TIPOMOBILIARIO" Type="eREST_MOBILIARIO" />
    </Type>
  </Table>
  <Table Name="dbo.eREST_USUARIO" Member="eREST_USUARIOs">
    <Type Name="eREST_USUARIO">
      <Column Name="USU_PK_USUARIO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USU_FK_PERSONA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USU_FK_ROL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USU_NOMBRE_USAURIO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="USU_CLAVE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="USU_FK_EMPLEADO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USU_ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="eREST_USUARIO_eREST_ORDEN" Member="eREST_ORDENs" ThisKey="USU_PK_USUARIO" OtherKey="ORD_FK_USUARIO" Type="eREST_ORDEN" />
    </Type>
  </Table>
</Database>