//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eREST.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OthersResoures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OthersResoures() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eREST.Resources.OthersResoures", typeof(OthersResoures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Icons/Others/ApprovedPosition.png.
        /// </summary>
        internal static string ApprovedPosition {
            get {
                return ResourceManager.GetString("ApprovedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Images/ComponentsBar/B.png.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Icons/Others/DeniedPosition.png.
        /// </summary>
        internal static string DeniedPosition {
            get {
                return ResourceManager.GetString("DeniedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Images/ComponentsBar/M4.png.
        /// </summary>
        internal static string M4 {
            get {
                return ResourceManager.GetString("M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Images/ComponentsBar/M6.png.
        /// </summary>
        internal static string M6 {
            get {
                return ResourceManager.GetString("M6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Images/Others/Border.png.
        /// </summary>
        internal static string noProductImage {
            get {
                return ResourceManager.GetString("noProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /eREST;component/Images/ComponentsBar/P.png.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
    }
}
